# Page title
page_title                                : hexit

# App Info
ios_app_id                                :                                           # TODO: Add App Store ID once available
ios_app_country                           : it

appstore_link                             :                                           # TODO: Add App Store link once available
playstore_link                            :
presskit_download_link                    :

app_icon                                  : assets/appicon.png
app_name                                  : hexit
app_price                                 : Free
app_description                           : Train your color eye in minutes a day.

enable_smart_app_banner                   : true

# Information About Yourself
your_name                                 : keinEntwickler
your_link                                 : https://github.com/keinEntwickler
your_city                                 :
email_address                             : appstore-keinentwickler@pm.me
linkedin_username                         :
linkedin_company                          :
facebook_username                         :
instagram_username                        :
twitter_username                          : keinentwickler
github_username                           : keinEntwickler
youtube_username                          :
mastodon_link                             :

# Base URL for GitHub Pages
baseurl                                   : /hexit-landing-page
url                                       : https://keinentwickler.github.io

# Supported languages
languages:
  - code: en
    name: English
    flag: "\U0001F1EC\U0001F1E7"
  - code: de
    name: Deutsch
    flag: "\U0001F1E9\U0001F1EA"
  - code: it
    name: Italiano
    flag: "\U0001F1EE\U0001F1F9"
  - code: fr
    name: "Fran\u00E7ais"
    flag: "\U0001F1EB\U0001F1F7"
  - code: es
    name: "Espa\u00F1ol"
    flag: "\U0001F1EA\U0001F1F8"
  - code: zh-Hans
    name: "\u4E2D\u6587"
    flag: "\U0001F1E8\U0001F1F3"

default_lang: en

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#e94560"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#e94560"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
